FROM mcr.microsoft.com/windows/servercore:ltsc2022 

WORKDIR "C:\Users\Administrator\Downloads"
COPY OpenJDK17U-jdk_x64_windows_hotspot_17.0.4.1_1.msi java.msi
RUN msiexec /i java.msi ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome,FeatureOracleJavaSoft INSTALLDIR="c:\Program Files\Temurin\" /quiet

 